### ISSUE TITLE
Install Graphviz Portable Along With SchemaCrawler

### ISSUE THREAD

**Issue by sualeh** [adriens/chocolatey-schemacrawler#2]
Install [Chocolatey Graphviz Portable](https://chocolatey.org/packages/graphviz.portable) along with SchemaCrawler

**Comment by adriens** [comment]
Hi @sualeh , finally you found the surprise before package approval ;-p

Could you tell me why we should replace [graphviz](https://chocolatey.org/packages/Graphviz) by [graphviz.portable](https://chocolatey.org/packages/graphviz.portable) ?

From what i can see, the portable seems to get more updates (ie. better maintained) than ```graphviz``` : 

11/19/2017 vs 2/9/2018 .... or is it the fact that it is portable ? Please let me know and i patch this 😸

**Comment by adriens** [comment]
Ok, got the why, will switch on the portable very soon
https://chocolatey.org/faq#what-distinction-does-chocolatey-make-between-an-installable-and-a-portable-application
