### ISSUE TITLE
Support SchemaCrawler 15.03.01

### ISSUE THREAD

**Issue by sualeh** [adriens/chocolatey-schemacrawler#31]
# New SchemaCrawler release

Please release the choco package for latest SchemaCrawler `15.03.01`

# Want to make release faster ?

1 - Modify [schemacrawler.properties](schemacrawler.properties) with the target version
2 - Make a *PR*

**Comment by adriens** [comment]
Great, thanks for the issue @sualeh :clap:

**Comment by adriens** [comment]
Waiting for moderation :pause_button:

**Comment by adriens** [comment]
Done.
