### ISSUE TITLE
Transfer Ownership of Chocolatey Account

### ISSUE THREAD

**Issue by sualeh** [adriens/chocolatey-schemacrawler#77]
@adriens - thank you so much for taking the trouble to create the Chocolatey installer for SchemaCrawler, and for maintaining it with immediate releases every time a new version is released. I think that with JReleaser, it will be less work for both of us to automatically release new SchemaCrawler version. Please could you transfer the ownership of the Chocolatey account to me - `sualeh` ? Thank you so much!

**Comment by adriens** [comment]
Hey Sualeh, yes, of course.

Can you please provide me your Chocolatey username please ?

![image](https://user-images.githubusercontent.com/5235127/150697987-abfd1254-f837-4723-afbe-d80840d5993a.png)

**Comment by sualeh** [comment]
sualeh

**Comment by adriens** [comment]
⚡ 
![image](https://user-images.githubusercontent.com/5235127/150698036-7205e495-6c7c-47b6-bd1b-c92800e75061.png)

**Comment by sualeh** [comment]
Thanks. Got it!

**Comment by adriens** [comment]
🚀 🙏

**Comment by adriens** [comment]
I've removed your personal email address from the issue 👍

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/150698806-ec75548f-123e-4d9d-9b4b-19e36a71336d.png)

**Comment by aalmiray** [comment]
FWIW @sualeh JReleaser can setup a github repository with a GH workflow to build the nuget package and push it to the community access point.

**Comment by adriens** [comment]
> FWIW @sualeh JReleaser can setup a github repository with a GH workflow to build the nuget package and push it to the community access point.

Thanks a lot for pointing this @aalmiray 💯

**Comment by sualeh** [comment]
Thanks for letting me know, @aalmiray - I will try that out right away.

**Comment by sualeh** [comment]
@adriens - getting there with the automated Chocolatey release process:
https://community.chocolatey.org/packages/schemacrawler/16.16.10#status

**Comment by adriens** [comment]
yep, I saw some feedbacks about email address and nuspec file
🤞  the JReleaser automated process will be validated soo for choco 😸
